"""Testi inglesi: interfaccia (UI), formattazione (FMT), terminale (CLI).

Gemello di lang_it.py, con le stesse identiche chiavi. Le convenzioni (solo
dati, niente entita' HTML, dove va ogni dizionario) sono spiegate nel
docstring di lang_it.py; il disegno complessivo in quello di i18n.py.

Quando si aggiunge una chiave, la si aggiunge in ENTRAMBI i file. Se manca
qui, la pagina inglese mostrera' il nome della chiave: e' voluto, perche' si
veda subito.

[EN] English texts: interface (UI), formatting (FMT), terminal (CLI).

Twin of lang_it.py, with exactly the same keys. The conventions (data
only, no HTML entities, where each dictionary goes) are explained in
lang_it.py's docstring; the overall design in i18n.py's.

When adding a key, add it to BOTH files. If it is missing here, the
English page will show the key name: that is deliberate, so it is
noticed immediately.
"""

# ------------------------------------------------------------------
# UI -- tutto cio' che si vede nelle tre pagine.
# [EN] UI -- everything visible on the three pages.
# ------------------------------------------------------------------
UI = {
    "page": {
        "dashboard": "Claude Code — Token usage",
        "pricing": "Price list — Claude Code",
        "guide": "Cost optimisation guide — Claude Code",
    },

    "header": {
        "brandTag": "Token & Cost Monitoring",
        "updatedTitle": "Date and time of the last update",
        "updated": "Updated",
        "refreshTitle": "Reload the data keeping the chosen filters",
        "refresh": "Refresh",
        "nav": "Main navigation",
        "langSwitch": "Page language",
    },

    "dash": {
        "h1": "Token usage — Claude Code",
        "desc": "Detailed monitoring of usage, estimated costs and "
                "interactions per session",
    },

    # Vedi lang_it.py: questi tre paragrafi viaggiano su data-i18n-html,
    # quindi il markup e le entita' HTML qui dentro sono voluti.
    # [EN] See lang_it.py: these three paragraphs travel on data-i18n-html,
    # so the markup and the HTML entities in here are intended.
    "help": {
        "summary": "How many tokens does this monitoring system use?",
        "p1": "The logging (the hooks writing <code>tokens.csv</code> and "
              "<code>operations.csv</code>, plus the regeneration of this "
              "page) never calls the Claude API: it only reads files already "
              "saved locally and writes local files. <strong>Tokens used: "
              "zero.</strong>",
        "p2": "The hooks never return messages that end up in the "
              "conversation context (no <code>systemMessage</code> or "
              "<code>additionalContext</code>), so they do not add a single "
              "token to future turns, neither in this session nor in later "
              "ones.",
        "p3": "The only cost is local and not monetary: at every tool call "
              "and at the end of every turn the scripts re-read the session "
              "transcript to compute the usage deltas. It grows slightly with "
              "the length of the session, but stays in the order of "
              "milliseconds &mdash; an imperceptible wait, not a dent in your "
              "wallet.",
    },

    "side": {
        "filters": "Filters",
        "unit": "Unit",
    },

    "filters": {
        "projects": "Projects:",
        "session": "Session:",
        "account": "Account:",
        "period": "Period:",
        "model": "Model:",
        "search": "Search in the request:",
        "searchPlaceholder": "Request text…",
        "searchClear": "Clear the search",
    },

    "unit": {
        "usd": "Dollars",
        "eur": "Euros",
        "tokens": "Tokens",
    },

    "chart": {
        "groupBy": "Group by:",
        "byDay": "By day",
        "byMonth": "By month",
        "bySession": "By session",
        "byProject": "By project",
        "byModel": "By model",
        "aggregate": "Aggregate",
        "mode": "Mode:",
        "scale": "Scale:",
        "linear": "Linear",
        "log": "Log",
        "period": "Period:",
        "rangeAria": "Width of the time window",
    },

    "turns": {
        "recent": "Recent interactions",
        "colTs": "Date and time",
        "colSession": "Session",
        "colRequest": "Request",
        "colModel": "Model",
        "colTotal": "Total",
        "colCost": "Cost",
        "paginationAria": "Interactions pagination",
        "rows": "Rows:",
    },

    "footer": {
        "generated": "File generated by ~/.claude/hooks/generate_dashboard/, "
                     "invoked by the Stop hook.",
    },

    "nav": {
        "dashboard": "Dashboard",
        "pricing": "Pricing",
        "guide": "Cost guide",
    },
}


# ------------------------------------------------------------------
# FMT -- come si scrivono numeri, valute e date in questa lingua.
# Vedi lang_it.py per il significato di ogni chiave.
# [EN] FMT -- how numbers, currencies and dates are written in this
# language. See lang_it.py for the meaning of each key.
# ------------------------------------------------------------------
FMT = {
    # Punto per i decimali, virgola per le migliaia: 1,234.56.
    # [EN] Dot for decimals, comma for thousands: 1,234.56.
    "dec": ".",
    "thou": ",",

    # Il simbolo di valuta va DAVANTI e attaccato: "$12.50". Per questo
    # il pezzo anteriore e' pieno e quello posteriore vuoto -- lo
    # specchio esatto dell'italiano.
    # [EN] The currency symbol goes IN FRONT and attached: "$12.50".
    # Hence the front piece is filled and the back one empty -- the exact
    # mirror of Italian.
    "moneyPre": "$",
    "moneyPostUsd": "",
    "moneyPostEur": "",

    # "B" per billion. Vedi la nota sul falso amico in lang_it.py.
    # [EN] "B" for billion. See the false-friend note in lang_it.py.
    "billion": "B",

    # Mesi in inglese: maiuscoli, come vuole la lingua.
    # [EN] Months in English: capitalised, as the language requires.
    "monthsShort": [
        "Jan", "Feb", "Mar", "Apr", "May", "Jun",
        "Jul", "Aug", "Sep", "Oct", "Nov", "Dec",
    ],
    "monthsLong": [
        "January", "February", "March", "April", "May", "June",
        "July", "August", "September", "October", "November", "December",
    ],
}


# ------------------------------------------------------------------
# CLI -- i messaggi stampati a terminale. Non arrivano mai al browser.
# [EN] CLI -- the messages printed to the terminal. They never reach the
# browser.
# ------------------------------------------------------------------
CLI = {}
